---
  logging:
    log_freq: 50
    log_plot_freq: 10
    info_prints: true
    wandb: true

  paths:
    data_dir: "data"
    data_file: "0001_64k_real_spectra_15x15_spot.root"
    checkpoint_dir: "checkpoints"
    checkpoint: "checkpoint.pth.tar"
    best_checkpoint: "best.pth.tar"
  
  data:
    batch_size: 64
    num_workers: 4
    test_size: 0.2
  
  model:
    tag: "MyModel"
    use_checkpoint: "no" # one of "no", "last", "best"
    output_positive: true
    n_scales: 4
    hidden_dim: 2
  
  training:
    num_epochs: 100
    optimizer:
      learning_rate: 0.001
      weight_decay: 0.01
    scheduler:
      tag: "StepLR"
      step_size: 15
      gamma: 0.8
    loss_fn: "RMSLE" # one of "RMSE_E", "MAE_E", "MSE", "MAE", "RMSLE"
